//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AiresUtilerias.mx.pade.timbradoCorreo {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Timbrado40PortBinding", Namespace="timbrado.ws.pade.mx")]
    public partial class Timbrado40 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback cancelarConOpcionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback timbradoBase64OperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarPeticionesPendientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback enviarXmlAndPdfPorCorreoOperationCompleted;
        
        private System.Threading.SendOrPostCallback timbradoBase64PruebaOperationCompleted;
        
        private System.Threading.SendOrPostCallback timbradoConCSDOperationCompleted;
        
        private System.Threading.SendOrPostCallback timbradoCfdiOperationCompleted;
        
        private System.Threading.SendOrPostCallback timbradoOperationCompleted;
        
        private System.Threading.SendOrPostCallback responderSolicitudCancelacionConOpcionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarCfdiRelacionadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarEstatusComprobanteOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarDisponibilidadServicioOperationCompleted;
        
        private System.Threading.SendOrPostCallback timbradoPruebaOperationCompleted;
        
        private System.Threading.SendOrPostCallback cfdiPorUUIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback cfdiPorEmisorSerieFolioOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelarOperationCompleted;
        
        private System.Threading.SendOrPostCallback acuseCancelacionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Timbrado40() {
            this.Url = global::AiresUtilerias.Properties.Settings.Default.BotanasUtilerias_mx_pade_timbradoCorreo_Timbrado4_0;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event cancelarConOpcionesCompletedEventHandler cancelarConOpcionesCompleted;
        
        /// <remarks/>
        public event timbradoBase64CompletedEventHandler timbradoBase64Completed;
        
        /// <remarks/>
        public event consultarPeticionesPendientesCompletedEventHandler consultarPeticionesPendientesCompleted;
        
        /// <remarks/>
        public event enviarXmlAndPdfPorCorreoCompletedEventHandler enviarXmlAndPdfPorCorreoCompleted;
        
        /// <remarks/>
        public event timbradoBase64PruebaCompletedEventHandler timbradoBase64PruebaCompleted;
        
        /// <remarks/>
        public event timbradoConCSDCompletedEventHandler timbradoConCSDCompleted;
        
        /// <remarks/>
        public event timbradoCfdiCompletedEventHandler timbradoCfdiCompleted;
        
        /// <remarks/>
        public event timbradoCompletedEventHandler timbradoCompleted;
        
        /// <remarks/>
        public event responderSolicitudCancelacionConOpcionesCompletedEventHandler responderSolicitudCancelacionConOpcionesCompleted;
        
        /// <remarks/>
        public event consultarCfdiRelacionadosCompletedEventHandler consultarCfdiRelacionadosCompleted;
        
        /// <remarks/>
        public event consultarEstatusComprobanteCompletedEventHandler consultarEstatusComprobanteCompleted;
        
        /// <remarks/>
        public event consultarDisponibilidadServicioCompletedEventHandler consultarDisponibilidadServicioCompleted;
        
        /// <remarks/>
        public event timbradoPruebaCompletedEventHandler timbradoPruebaCompleted;
        
        /// <remarks/>
        public event cfdiPorUUIDCompletedEventHandler cfdiPorUUIDCompleted;
        
        /// <remarks/>
        public event cfdiPorEmisorSerieFolioCompletedEventHandler cfdiPorEmisorSerieFolioCompleted;
        
        /// <remarks/>
        public event cancelarCompletedEventHandler cancelarCompleted;
        
        /// <remarks/>
        public event acuseCancelacionCompletedEventHandler acuseCancelacionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="timbrado.ws.pade.mx", ResponseNamespace="timbrado.ws.pade.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cancelarConOpciones([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contrato, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcEmisor, [System.Xml.Serialization.XmlElementAttribute("arregloUUID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string[] arregloUUID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)] byte[] cert, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)] byte[] key, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string keyPass, [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string[] opciones) {
            object[] results = this.Invoke("cancelarConOpciones", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        rfcEmisor,
                        arregloUUID,
                        cert,
                        key,
                        keyPass,
                        opciones});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cancelarConOpcionesAsync(string contrato, string usuario, string passwd, string rfcEmisor, string[] arregloUUID, byte[] cert, byte[] key, string keyPass, string[] opciones) {
            this.cancelarConOpcionesAsync(contrato, usuario, passwd, rfcEmisor, arregloUUID, cert, key, keyPass, opciones, null);
        }
        
        /// <remarks/>
        public void cancelarConOpcionesAsync(string contrato, string usuario, string passwd, string rfcEmisor, string[] arregloUUID, byte[] cert, byte[] key, string keyPass, string[] opciones, object userState) {
            if ((this.cancelarConOpcionesOperationCompleted == null)) {
                this.cancelarConOpcionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelarConOpcionesOperationCompleted);
            }
            this.InvokeAsync("cancelarConOpciones", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        rfcEmisor,
                        arregloUUID,
                        cert,
                        key,
                        keyPass,
                        opciones}, this.cancelarConOpcionesOperationCompleted, userState);
        }
        
        private void OncancelarConOpcionesOperationCompleted(object arg) {
            if ((this.cancelarConOpcionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelarConOpcionesCompleted(this, new cancelarConOpcionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("timbradoBase64", RequestNamespace="timbrado.ws.pade.mx", ResponseNamespace="timbrado.ws.pade.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timbradoBase64([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contrato, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string cfdiXmlBase64, [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string[] opciones) {
            object[] results = this.Invoke("timbradoBase64", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        cfdiXmlBase64,
                        opciones});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void timbradoBase64Async(string contrato, string usuario, string passwd, string cfdiXmlBase64, string[] opciones) {
            this.timbradoBase64Async(contrato, usuario, passwd, cfdiXmlBase64, opciones, null);
        }
        
        /// <remarks/>
        public void timbradoBase64Async(string contrato, string usuario, string passwd, string cfdiXmlBase64, string[] opciones, object userState) {
            if ((this.timbradoBase64OperationCompleted == null)) {
                this.timbradoBase64OperationCompleted = new System.Threading.SendOrPostCallback(this.OntimbradoBase64OperationCompleted);
            }
            this.InvokeAsync("timbradoBase64", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        cfdiXmlBase64,
                        opciones}, this.timbradoBase64OperationCompleted, userState);
        }
        
        private void OntimbradoBase64OperationCompleted(object arg) {
            if ((this.timbradoBase64Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.timbradoBase64Completed(this, new timbradoBase64CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("consultarPeticionesPendientes", RequestNamespace="timbrado.ws.pade.mx", ResponseNamespace="timbrado.ws.pade.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consultarPeticionesPendientes([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contrato, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcReceptor, [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string[] opciones) {
            object[] results = this.Invoke("consultarPeticionesPendientes", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        rfcReceptor,
                        opciones});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultarPeticionesPendientesAsync(string contrato, string usuario, string passwd, string rfcReceptor, string[] opciones) {
            this.consultarPeticionesPendientesAsync(contrato, usuario, passwd, rfcReceptor, opciones, null);
        }
        
        /// <remarks/>
        public void consultarPeticionesPendientesAsync(string contrato, string usuario, string passwd, string rfcReceptor, string[] opciones, object userState) {
            if ((this.consultarPeticionesPendientesOperationCompleted == null)) {
                this.consultarPeticionesPendientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarPeticionesPendientesOperationCompleted);
            }
            this.InvokeAsync("consultarPeticionesPendientes", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        rfcReceptor,
                        opciones}, this.consultarPeticionesPendientesOperationCompleted, userState);
        }
        
        private void OnconsultarPeticionesPendientesOperationCompleted(object arg) {
            if ((this.consultarPeticionesPendientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarPeticionesPendientesCompleted(this, new consultarPeticionesPendientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="timbrado.ws.pade.mx", ResponseNamespace="timbrado.ws.pade.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string enviarXmlAndPdfPorCorreo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contrato, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string uuid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string destinatarios) {
            object[] results = this.Invoke("enviarXmlAndPdfPorCorreo", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        uuid,
                        destinatarios});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void enviarXmlAndPdfPorCorreoAsync(string contrato, string usuario, string passwd, string uuid, string destinatarios) {
            this.enviarXmlAndPdfPorCorreoAsync(contrato, usuario, passwd, uuid, destinatarios, null);
        }
        
        /// <remarks/>
        public void enviarXmlAndPdfPorCorreoAsync(string contrato, string usuario, string passwd, string uuid, string destinatarios, object userState) {
            if ((this.enviarXmlAndPdfPorCorreoOperationCompleted == null)) {
                this.enviarXmlAndPdfPorCorreoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnenviarXmlAndPdfPorCorreoOperationCompleted);
            }
            this.InvokeAsync("enviarXmlAndPdfPorCorreo", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        uuid,
                        destinatarios}, this.enviarXmlAndPdfPorCorreoOperationCompleted, userState);
        }
        
        private void OnenviarXmlAndPdfPorCorreoOperationCompleted(object arg) {
            if ((this.enviarXmlAndPdfPorCorreoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.enviarXmlAndPdfPorCorreoCompleted(this, new enviarXmlAndPdfPorCorreoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("timbradoBase64Prueba", RequestNamespace="timbrado.ws.pade.mx", ResponseNamespace="timbrado.ws.pade.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timbradoBase64Prueba([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contrato, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string cfdiXmlBase64, [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string[] opciones) {
            object[] results = this.Invoke("timbradoBase64Prueba", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        cfdiXmlBase64,
                        opciones});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void timbradoBase64PruebaAsync(string contrato, string usuario, string passwd, string cfdiXmlBase64, string[] opciones) {
            this.timbradoBase64PruebaAsync(contrato, usuario, passwd, cfdiXmlBase64, opciones, null);
        }
        
        /// <remarks/>
        public void timbradoBase64PruebaAsync(string contrato, string usuario, string passwd, string cfdiXmlBase64, string[] opciones, object userState) {
            if ((this.timbradoBase64PruebaOperationCompleted == null)) {
                this.timbradoBase64PruebaOperationCompleted = new System.Threading.SendOrPostCallback(this.OntimbradoBase64PruebaOperationCompleted);
            }
            this.InvokeAsync("timbradoBase64Prueba", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        cfdiXmlBase64,
                        opciones}, this.timbradoBase64PruebaOperationCompleted, userState);
        }
        
        private void OntimbradoBase64PruebaOperationCompleted(object arg) {
            if ((this.timbradoBase64PruebaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.timbradoBase64PruebaCompleted(this, new timbradoBase64PruebaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("timbradoConCSD", RequestNamespace="timbrado.ws.pade.mx", ResponseNamespace="timbrado.ws.pade.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timbradoConCSD([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contrato, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string cfdiXml, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)] byte[] cert, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)] byte[] key, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string keyPass, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool prueba, [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string[] opciones) {
            object[] results = this.Invoke("timbradoConCSD", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        cfdiXml,
                        cert,
                        key,
                        keyPass,
                        prueba,
                        opciones});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void timbradoConCSDAsync(string contrato, string usuario, string passwd, string cfdiXml, byte[] cert, byte[] key, string keyPass, bool prueba, string[] opciones) {
            this.timbradoConCSDAsync(contrato, usuario, passwd, cfdiXml, cert, key, keyPass, prueba, opciones, null);
        }
        
        /// <remarks/>
        public void timbradoConCSDAsync(string contrato, string usuario, string passwd, string cfdiXml, byte[] cert, byte[] key, string keyPass, bool prueba, string[] opciones, object userState) {
            if ((this.timbradoConCSDOperationCompleted == null)) {
                this.timbradoConCSDOperationCompleted = new System.Threading.SendOrPostCallback(this.OntimbradoConCSDOperationCompleted);
            }
            this.InvokeAsync("timbradoConCSD", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        cfdiXml,
                        cert,
                        key,
                        keyPass,
                        prueba,
                        opciones}, this.timbradoConCSDOperationCompleted, userState);
        }
        
        private void OntimbradoConCSDOperationCompleted(object arg) {
            if ((this.timbradoConCSDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.timbradoConCSDCompleted(this, new timbradoConCSDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("timbradoCfdi", RequestNamespace="timbrado.ws.pade.mx", ResponseNamespace="timbrado.ws.pade.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timbradoCfdi([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contrato, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string cfdiXml, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)] byte[] cert, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)] byte[] key, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string keyPass, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool prueba, [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string[] opciones) {
            object[] results = this.Invoke("timbradoCfdi", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        cfdiXml,
                        cert,
                        key,
                        keyPass,
                        prueba,
                        opciones});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void timbradoCfdiAsync(string contrato, string usuario, string passwd, string cfdiXml, byte[] cert, byte[] key, string keyPass, bool prueba, string[] opciones) {
            this.timbradoCfdiAsync(contrato, usuario, passwd, cfdiXml, cert, key, keyPass, prueba, opciones, null);
        }
        
        /// <remarks/>
        public void timbradoCfdiAsync(string contrato, string usuario, string passwd, string cfdiXml, byte[] cert, byte[] key, string keyPass, bool prueba, string[] opciones, object userState) {
            if ((this.timbradoCfdiOperationCompleted == null)) {
                this.timbradoCfdiOperationCompleted = new System.Threading.SendOrPostCallback(this.OntimbradoCfdiOperationCompleted);
            }
            this.InvokeAsync("timbradoCfdi", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        cfdiXml,
                        cert,
                        key,
                        keyPass,
                        prueba,
                        opciones}, this.timbradoCfdiOperationCompleted, userState);
        }
        
        private void OntimbradoCfdiOperationCompleted(object arg) {
            if ((this.timbradoCfdiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.timbradoCfdiCompleted(this, new timbradoCfdiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("timbrado", RequestNamespace="timbrado.ws.pade.mx", ResponseNamespace="timbrado.ws.pade.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timbrado([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contrato, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string cfdiXml, [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string[] opciones) {
            object[] results = this.Invoke("timbrado", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        cfdiXml,
                        opciones});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void timbradoAsync(string contrato, string usuario, string passwd, string cfdiXml, string[] opciones) {
            this.timbradoAsync(contrato, usuario, passwd, cfdiXml, opciones, null);
        }
        
        /// <remarks/>
        public void timbradoAsync(string contrato, string usuario, string passwd, string cfdiXml, string[] opciones, object userState) {
            if ((this.timbradoOperationCompleted == null)) {
                this.timbradoOperationCompleted = new System.Threading.SendOrPostCallback(this.OntimbradoOperationCompleted);
            }
            this.InvokeAsync("timbrado", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        cfdiXml,
                        opciones}, this.timbradoOperationCompleted, userState);
        }
        
        private void OntimbradoOperationCompleted(object arg) {
            if ((this.timbradoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.timbradoCompleted(this, new timbradoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("responderSolicitudCancelacionConOpciones", RequestNamespace="timbrado.ws.pade.mx", ResponseNamespace="timbrado.ws.pade.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string responderSolicitudCancelacionConOpciones([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contrato, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcReceptor, [System.Xml.Serialization.XmlElementAttribute("arregloUUID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string[] arregloUUID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)] byte[] cert, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)] byte[] key, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string keyPass, [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string[] opciones) {
            object[] results = this.Invoke("responderSolicitudCancelacionConOpciones", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        rfcReceptor,
                        arregloUUID,
                        cert,
                        key,
                        keyPass,
                        opciones});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void responderSolicitudCancelacionConOpcionesAsync(string contrato, string usuario, string passwd, string rfcReceptor, string[] arregloUUID, byte[] cert, byte[] key, string keyPass, string[] opciones) {
            this.responderSolicitudCancelacionConOpcionesAsync(contrato, usuario, passwd, rfcReceptor, arregloUUID, cert, key, keyPass, opciones, null);
        }
        
        /// <remarks/>
        public void responderSolicitudCancelacionConOpcionesAsync(string contrato, string usuario, string passwd, string rfcReceptor, string[] arregloUUID, byte[] cert, byte[] key, string keyPass, string[] opciones, object userState) {
            if ((this.responderSolicitudCancelacionConOpcionesOperationCompleted == null)) {
                this.responderSolicitudCancelacionConOpcionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnresponderSolicitudCancelacionConOpcionesOperationCompleted);
            }
            this.InvokeAsync("responderSolicitudCancelacionConOpciones", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        rfcReceptor,
                        arregloUUID,
                        cert,
                        key,
                        keyPass,
                        opciones}, this.responderSolicitudCancelacionConOpcionesOperationCompleted, userState);
        }
        
        private void OnresponderSolicitudCancelacionConOpcionesOperationCompleted(object arg) {
            if ((this.responderSolicitudCancelacionConOpcionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.responderSolicitudCancelacionConOpcionesCompleted(this, new responderSolicitudCancelacionConOpcionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("consultarCfdiRelacionados", RequestNamespace="timbrado.ws.pade.mx", ResponseNamespace="timbrado.ws.pade.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consultarCfdiRelacionados([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contrato, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcEmisor, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcReceptor, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string uuid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)] byte[] cert, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)] byte[] key, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string keyPass, [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string[] opciones) {
            object[] results = this.Invoke("consultarCfdiRelacionados", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        rfcEmisor,
                        rfcReceptor,
                        uuid,
                        cert,
                        key,
                        keyPass,
                        opciones});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultarCfdiRelacionadosAsync(string contrato, string usuario, string passwd, string rfcEmisor, string rfcReceptor, string uuid, byte[] cert, byte[] key, string keyPass, string[] opciones) {
            this.consultarCfdiRelacionadosAsync(contrato, usuario, passwd, rfcEmisor, rfcReceptor, uuid, cert, key, keyPass, opciones, null);
        }
        
        /// <remarks/>
        public void consultarCfdiRelacionadosAsync(string contrato, string usuario, string passwd, string rfcEmisor, string rfcReceptor, string uuid, byte[] cert, byte[] key, string keyPass, string[] opciones, object userState) {
            if ((this.consultarCfdiRelacionadosOperationCompleted == null)) {
                this.consultarCfdiRelacionadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarCfdiRelacionadosOperationCompleted);
            }
            this.InvokeAsync("consultarCfdiRelacionados", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        rfcEmisor,
                        rfcReceptor,
                        uuid,
                        cert,
                        key,
                        keyPass,
                        opciones}, this.consultarCfdiRelacionadosOperationCompleted, userState);
        }
        
        private void OnconsultarCfdiRelacionadosOperationCompleted(object arg) {
            if ((this.consultarCfdiRelacionadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarCfdiRelacionadosCompleted(this, new consultarCfdiRelacionadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("consultarEstatusComprobante", RequestNamespace="timbrado.ws.pade.mx", ResponseNamespace="timbrado.ws.pade.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consultarEstatusComprobante([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contrato, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string uuid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcEmisor, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcReceptor, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string total, [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string[] opciones) {
            object[] results = this.Invoke("consultarEstatusComprobante", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        uuid,
                        rfcEmisor,
                        rfcReceptor,
                        total,
                        opciones});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultarEstatusComprobanteAsync(string contrato, string usuario, string passwd, string uuid, string rfcEmisor, string rfcReceptor, string total, string[] opciones) {
            this.consultarEstatusComprobanteAsync(contrato, usuario, passwd, uuid, rfcEmisor, rfcReceptor, total, opciones, null);
        }
        
        /// <remarks/>
        public void consultarEstatusComprobanteAsync(string contrato, string usuario, string passwd, string uuid, string rfcEmisor, string rfcReceptor, string total, string[] opciones, object userState) {
            if ((this.consultarEstatusComprobanteOperationCompleted == null)) {
                this.consultarEstatusComprobanteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarEstatusComprobanteOperationCompleted);
            }
            this.InvokeAsync("consultarEstatusComprobante", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        uuid,
                        rfcEmisor,
                        rfcReceptor,
                        total,
                        opciones}, this.consultarEstatusComprobanteOperationCompleted, userState);
        }
        
        private void OnconsultarEstatusComprobanteOperationCompleted(object arg) {
            if ((this.consultarEstatusComprobanteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarEstatusComprobanteCompleted(this, new consultarEstatusComprobanteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="timbrado.ws.pade.mx", ResponseNamespace="timbrado.ws.pade.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public resultDisponibilidadServicio consultarDisponibilidadServicio([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contrato, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwd) {
            object[] results = this.Invoke("consultarDisponibilidadServicio", new object[] {
                        contrato,
                        usuario,
                        passwd});
            return ((resultDisponibilidadServicio)(results[0]));
        }
        
        /// <remarks/>
        public void consultarDisponibilidadServicioAsync(string contrato, string usuario, string passwd) {
            this.consultarDisponibilidadServicioAsync(contrato, usuario, passwd, null);
        }
        
        /// <remarks/>
        public void consultarDisponibilidadServicioAsync(string contrato, string usuario, string passwd, object userState) {
            if ((this.consultarDisponibilidadServicioOperationCompleted == null)) {
                this.consultarDisponibilidadServicioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarDisponibilidadServicioOperationCompleted);
            }
            this.InvokeAsync("consultarDisponibilidadServicio", new object[] {
                        contrato,
                        usuario,
                        passwd}, this.consultarDisponibilidadServicioOperationCompleted, userState);
        }
        
        private void OnconsultarDisponibilidadServicioOperationCompleted(object arg) {
            if ((this.consultarDisponibilidadServicioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarDisponibilidadServicioCompleted(this, new consultarDisponibilidadServicioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("timbradoPrueba", RequestNamespace="timbrado.ws.pade.mx", ResponseNamespace="timbrado.ws.pade.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string timbradoPrueba([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contrato, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string cfdiXml, [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string[] opciones) {
            object[] results = this.Invoke("timbradoPrueba", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        cfdiXml,
                        opciones});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void timbradoPruebaAsync(string contrato, string usuario, string passwd, string cfdiXml, string[] opciones) {
            this.timbradoPruebaAsync(contrato, usuario, passwd, cfdiXml, opciones, null);
        }
        
        /// <remarks/>
        public void timbradoPruebaAsync(string contrato, string usuario, string passwd, string cfdiXml, string[] opciones, object userState) {
            if ((this.timbradoPruebaOperationCompleted == null)) {
                this.timbradoPruebaOperationCompleted = new System.Threading.SendOrPostCallback(this.OntimbradoPruebaOperationCompleted);
            }
            this.InvokeAsync("timbradoPrueba", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        cfdiXml,
                        opciones}, this.timbradoPruebaOperationCompleted, userState);
        }
        
        private void OntimbradoPruebaOperationCompleted(object arg) {
            if ((this.timbradoPruebaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.timbradoPruebaCompleted(this, new timbradoPruebaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="timbrado.ws.pade.mx", ResponseNamespace="timbrado.ws.pade.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cfdiPorUUID([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contrato, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string uuid) {
            object[] results = this.Invoke("cfdiPorUUID", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        uuid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cfdiPorUUIDAsync(string contrato, string usuario, string passwd, string uuid) {
            this.cfdiPorUUIDAsync(contrato, usuario, passwd, uuid, null);
        }
        
        /// <remarks/>
        public void cfdiPorUUIDAsync(string contrato, string usuario, string passwd, string uuid, object userState) {
            if ((this.cfdiPorUUIDOperationCompleted == null)) {
                this.cfdiPorUUIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OncfdiPorUUIDOperationCompleted);
            }
            this.InvokeAsync("cfdiPorUUID", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        uuid}, this.cfdiPorUUIDOperationCompleted, userState);
        }
        
        private void OncfdiPorUUIDOperationCompleted(object arg) {
            if ((this.cfdiPorUUIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cfdiPorUUIDCompleted(this, new cfdiPorUUIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="timbrado.ws.pade.mx", ResponseNamespace="timbrado.ws.pade.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cfdiPorEmisorSerieFolio([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contrato, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcEmisor, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string serie, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string folio) {
            object[] results = this.Invoke("cfdiPorEmisorSerieFolio", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        rfcEmisor,
                        serie,
                        folio});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cfdiPorEmisorSerieFolioAsync(string contrato, string usuario, string passwd, string rfcEmisor, string serie, string folio) {
            this.cfdiPorEmisorSerieFolioAsync(contrato, usuario, passwd, rfcEmisor, serie, folio, null);
        }
        
        /// <remarks/>
        public void cfdiPorEmisorSerieFolioAsync(string contrato, string usuario, string passwd, string rfcEmisor, string serie, string folio, object userState) {
            if ((this.cfdiPorEmisorSerieFolioOperationCompleted == null)) {
                this.cfdiPorEmisorSerieFolioOperationCompleted = new System.Threading.SendOrPostCallback(this.OncfdiPorEmisorSerieFolioOperationCompleted);
            }
            this.InvokeAsync("cfdiPorEmisorSerieFolio", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        rfcEmisor,
                        serie,
                        folio}, this.cfdiPorEmisorSerieFolioOperationCompleted, userState);
        }
        
        private void OncfdiPorEmisorSerieFolioOperationCompleted(object arg) {
            if ((this.cfdiPorEmisorSerieFolioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cfdiPorEmisorSerieFolioCompleted(this, new cfdiPorEmisorSerieFolioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="timbrado.ws.pade.mx", ResponseNamespace="timbrado.ws.pade.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cancelar([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contrato, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcEmisor, [System.Xml.Serialization.XmlElementAttribute("arregloUUID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string[] arregloUUID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)] byte[] cert, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)] byte[] key, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string keyPass) {
            object[] results = this.Invoke("cancelar", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        rfcEmisor,
                        arregloUUID,
                        cert,
                        key,
                        keyPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cancelarAsync(string contrato, string usuario, string passwd, string rfcEmisor, string[] arregloUUID, byte[] cert, byte[] key, string keyPass) {
            this.cancelarAsync(contrato, usuario, passwd, rfcEmisor, arregloUUID, cert, key, keyPass, null);
        }
        
        /// <remarks/>
        public void cancelarAsync(string contrato, string usuario, string passwd, string rfcEmisor, string[] arregloUUID, byte[] cert, byte[] key, string keyPass, object userState) {
            if ((this.cancelarOperationCompleted == null)) {
                this.cancelarOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelarOperationCompleted);
            }
            this.InvokeAsync("cancelar", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        rfcEmisor,
                        arregloUUID,
                        cert,
                        key,
                        keyPass}, this.cancelarOperationCompleted, userState);
        }
        
        private void OncancelarOperationCompleted(object arg) {
            if ((this.cancelarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelarCompleted(this, new cancelarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="timbrado.ws.pade.mx", ResponseNamespace="timbrado.ws.pade.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string acuseCancelacion([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contrato, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string uuid) {
            object[] results = this.Invoke("acuseCancelacion", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        uuid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void acuseCancelacionAsync(string contrato, string usuario, string passwd, string uuid) {
            this.acuseCancelacionAsync(contrato, usuario, passwd, uuid, null);
        }
        
        /// <remarks/>
        public void acuseCancelacionAsync(string contrato, string usuario, string passwd, string uuid, object userState) {
            if ((this.acuseCancelacionOperationCompleted == null)) {
                this.acuseCancelacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnacuseCancelacionOperationCompleted);
            }
            this.InvokeAsync("acuseCancelacion", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        uuid}, this.acuseCancelacionOperationCompleted, userState);
        }
        
        private void OnacuseCancelacionOperationCompleted(object arg) {
            if ((this.acuseCancelacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.acuseCancelacionCompleted(this, new acuseCancelacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="timbrado.ws.pade.mx")]
    public partial class resultDisponibilidadServicio {
        
        private string mensajeField;
        
        private bool servicioOkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool servicioOk {
            get {
                return this.servicioOkField;
            }
            set {
                this.servicioOkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void cancelarConOpcionesCompletedEventHandler(object sender, cancelarConOpcionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelarConOpcionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelarConOpcionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void timbradoBase64CompletedEventHandler(object sender, timbradoBase64CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class timbradoBase64CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal timbradoBase64CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void consultarPeticionesPendientesCompletedEventHandler(object sender, consultarPeticionesPendientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarPeticionesPendientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarPeticionesPendientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void enviarXmlAndPdfPorCorreoCompletedEventHandler(object sender, enviarXmlAndPdfPorCorreoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class enviarXmlAndPdfPorCorreoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal enviarXmlAndPdfPorCorreoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void timbradoBase64PruebaCompletedEventHandler(object sender, timbradoBase64PruebaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class timbradoBase64PruebaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal timbradoBase64PruebaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void timbradoConCSDCompletedEventHandler(object sender, timbradoConCSDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class timbradoConCSDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal timbradoConCSDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void timbradoCfdiCompletedEventHandler(object sender, timbradoCfdiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class timbradoCfdiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal timbradoCfdiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void timbradoCompletedEventHandler(object sender, timbradoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class timbradoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal timbradoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void responderSolicitudCancelacionConOpcionesCompletedEventHandler(object sender, responderSolicitudCancelacionConOpcionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class responderSolicitudCancelacionConOpcionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal responderSolicitudCancelacionConOpcionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void consultarCfdiRelacionadosCompletedEventHandler(object sender, consultarCfdiRelacionadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarCfdiRelacionadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarCfdiRelacionadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void consultarEstatusComprobanteCompletedEventHandler(object sender, consultarEstatusComprobanteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarEstatusComprobanteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarEstatusComprobanteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void consultarDisponibilidadServicioCompletedEventHandler(object sender, consultarDisponibilidadServicioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarDisponibilidadServicioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarDisponibilidadServicioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public resultDisponibilidadServicio Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((resultDisponibilidadServicio)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void timbradoPruebaCompletedEventHandler(object sender, timbradoPruebaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class timbradoPruebaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal timbradoPruebaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void cfdiPorUUIDCompletedEventHandler(object sender, cfdiPorUUIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cfdiPorUUIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cfdiPorUUIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void cfdiPorEmisorSerieFolioCompletedEventHandler(object sender, cfdiPorEmisorSerieFolioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cfdiPorEmisorSerieFolioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cfdiPorEmisorSerieFolioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void cancelarCompletedEventHandler(object sender, cancelarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void acuseCancelacionCompletedEventHandler(object sender, acuseCancelacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class acuseCancelacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal acuseCancelacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591