//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AiresUtilerias.mx.pade.timbrado {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IntegracionCfdiPortBinding", Namespace="integracionCfdi.ws.pade.mx")]
    public partial class IntegracionCfdi : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback cancelarCfdiOperationCompleted;
        
        private System.Threading.SendOrPostCallback procesarArchivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback obtenerXmlDesdeCsvOperationCompleted;
        
        private System.Threading.SendOrPostCallback procesarArchivoConCSDOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelarCfdiConOpcionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback acuseCancelacionCfdiOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaCfdiPorUUIDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IntegracionCfdi() {
            this.Url = global::AiresUtilerias.Properties.Settings.Default.BotanasUtilerias_mx_pade_timbrado_IntegracionCfdi;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event cancelarCfdiCompletedEventHandler cancelarCfdiCompleted;
        
        /// <remarks/>
        public event procesarArchivoCompletedEventHandler procesarArchivoCompleted;
        
        /// <remarks/>
        public event obtenerXmlDesdeCsvCompletedEventHandler obtenerXmlDesdeCsvCompleted;
        
        /// <remarks/>
        public event procesarArchivoConCSDCompletedEventHandler procesarArchivoConCSDCompleted;
        
        /// <remarks/>
        public event cancelarCfdiConOpcionesCompletedEventHandler cancelarCfdiConOpcionesCompleted;
        
        /// <remarks/>
        public event acuseCancelacionCfdiCompletedEventHandler acuseCancelacionCfdiCompleted;
        
        /// <remarks/>
        public event consultaCfdiPorUUIDCompletedEventHandler consultaCfdiPorUUIDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="integracionCfdi.ws.pade.mx", ResponseNamespace="integracionCfdi.ws.pade.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cancelarCfdi([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contrato, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcEmisor, [System.Xml.Serialization.XmlElementAttribute("arregloUUID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string[] arregloUUID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)] byte[] cert, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)] byte[] key, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string keyPass) {
            object[] results = this.Invoke("cancelarCfdi", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        rfcEmisor,
                        arregloUUID,
                        cert,
                        key,
                        keyPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cancelarCfdiAsync(string contrato, string usuario, string passwd, string rfcEmisor, string[] arregloUUID, byte[] cert, byte[] key, string keyPass) {
            this.cancelarCfdiAsync(contrato, usuario, passwd, rfcEmisor, arregloUUID, cert, key, keyPass, null);
        }
        
        /// <remarks/>
        public void cancelarCfdiAsync(string contrato, string usuario, string passwd, string rfcEmisor, string[] arregloUUID, byte[] cert, byte[] key, string keyPass, object userState) {
            if ((this.cancelarCfdiOperationCompleted == null)) {
                this.cancelarCfdiOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelarCfdiOperationCompleted);
            }
            this.InvokeAsync("cancelarCfdi", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        rfcEmisor,
                        arregloUUID,
                        cert,
                        key,
                        keyPass}, this.cancelarCfdiOperationCompleted, userState);
        }
        
        private void OncancelarCfdiOperationCompleted(object arg) {
            if ((this.cancelarCfdiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelarCfdiCompleted(this, new cancelarCfdiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="integracionCfdi.ws.pade.mx", ResponseNamespace="integracionCfdi.ws.pade.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string procesarArchivo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contrato, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool prueba, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string datos, [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string[] opciones) {
            object[] results = this.Invoke("procesarArchivo", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        prueba,
                        datos,
                        opciones});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void procesarArchivoAsync(string contrato, string usuario, string passwd, bool prueba, string datos, string[] opciones) {
            this.procesarArchivoAsync(contrato, usuario, passwd, prueba, datos, opciones, null);
        }
        
        /// <remarks/>
        public void procesarArchivoAsync(string contrato, string usuario, string passwd, bool prueba, string datos, string[] opciones, object userState) {
            if ((this.procesarArchivoOperationCompleted == null)) {
                this.procesarArchivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocesarArchivoOperationCompleted);
            }
            this.InvokeAsync("procesarArchivo", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        prueba,
                        datos,
                        opciones}, this.procesarArchivoOperationCompleted, userState);
        }
        
        private void OnprocesarArchivoOperationCompleted(object arg) {
            if ((this.procesarArchivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.procesarArchivoCompleted(this, new procesarArchivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="integracionCfdi.ws.pade.mx", ResponseNamespace="integracionCfdi.ws.pade.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string obtenerXmlDesdeCsv([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contrato, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string datos, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string plugin) {
            object[] results = this.Invoke("obtenerXmlDesdeCsv", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        datos,
                        plugin});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void obtenerXmlDesdeCsvAsync(string contrato, string usuario, string passwd, string datos, string plugin) {
            this.obtenerXmlDesdeCsvAsync(contrato, usuario, passwd, datos, plugin, null);
        }
        
        /// <remarks/>
        public void obtenerXmlDesdeCsvAsync(string contrato, string usuario, string passwd, string datos, string plugin, object userState) {
            if ((this.obtenerXmlDesdeCsvOperationCompleted == null)) {
                this.obtenerXmlDesdeCsvOperationCompleted = new System.Threading.SendOrPostCallback(this.OnobtenerXmlDesdeCsvOperationCompleted);
            }
            this.InvokeAsync("obtenerXmlDesdeCsv", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        datos,
                        plugin}, this.obtenerXmlDesdeCsvOperationCompleted, userState);
        }
        
        private void OnobtenerXmlDesdeCsvOperationCompleted(object arg) {
            if ((this.obtenerXmlDesdeCsvCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.obtenerXmlDesdeCsvCompleted(this, new obtenerXmlDesdeCsvCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="integracionCfdi.ws.pade.mx", ResponseNamespace="integracionCfdi.ws.pade.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string procesarArchivoConCSD([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contrato, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool prueba, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string datos, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)] byte[] cert, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)] byte[] key, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string keyPass, [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string[] opciones) {
            object[] results = this.Invoke("procesarArchivoConCSD", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        prueba,
                        datos,
                        cert,
                        key,
                        keyPass,
                        opciones});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void procesarArchivoConCSDAsync(string contrato, string usuario, string passwd, bool prueba, string datos, byte[] cert, byte[] key, string keyPass, string[] opciones) {
            this.procesarArchivoConCSDAsync(contrato, usuario, passwd, prueba, datos, cert, key, keyPass, opciones, null);
        }
        
        /// <remarks/>
        public void procesarArchivoConCSDAsync(string contrato, string usuario, string passwd, bool prueba, string datos, byte[] cert, byte[] key, string keyPass, string[] opciones, object userState) {
            if ((this.procesarArchivoConCSDOperationCompleted == null)) {
                this.procesarArchivoConCSDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocesarArchivoConCSDOperationCompleted);
            }
            this.InvokeAsync("procesarArchivoConCSD", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        prueba,
                        datos,
                        cert,
                        key,
                        keyPass,
                        opciones}, this.procesarArchivoConCSDOperationCompleted, userState);
        }
        
        private void OnprocesarArchivoConCSDOperationCompleted(object arg) {
            if ((this.procesarArchivoConCSDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.procesarArchivoConCSDCompleted(this, new procesarArchivoConCSDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="integracionCfdi.ws.pade.mx", ResponseNamespace="integracionCfdi.ws.pade.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cancelarCfdiConOpciones([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contrato, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcEmisor, [System.Xml.Serialization.XmlElementAttribute("arregloUUID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string[] arregloUUID, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)] byte[] cert, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)] byte[] key, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string keyPass, [System.Xml.Serialization.XmlElementAttribute("opciones", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string[] opciones) {
            object[] results = this.Invoke("cancelarCfdiConOpciones", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        rfcEmisor,
                        arregloUUID,
                        cert,
                        key,
                        keyPass,
                        opciones});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cancelarCfdiConOpcionesAsync(string contrato, string usuario, string passwd, string rfcEmisor, string[] arregloUUID, byte[] cert, byte[] key, string keyPass, string[] opciones) {
            this.cancelarCfdiConOpcionesAsync(contrato, usuario, passwd, rfcEmisor, arregloUUID, cert, key, keyPass, opciones, null);
        }
        
        /// <remarks/>
        public void cancelarCfdiConOpcionesAsync(string contrato, string usuario, string passwd, string rfcEmisor, string[] arregloUUID, byte[] cert, byte[] key, string keyPass, string[] opciones, object userState) {
            if ((this.cancelarCfdiConOpcionesOperationCompleted == null)) {
                this.cancelarCfdiConOpcionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelarCfdiConOpcionesOperationCompleted);
            }
            this.InvokeAsync("cancelarCfdiConOpciones", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        rfcEmisor,
                        arregloUUID,
                        cert,
                        key,
                        keyPass,
                        opciones}, this.cancelarCfdiConOpcionesOperationCompleted, userState);
        }
        
        private void OncancelarCfdiConOpcionesOperationCompleted(object arg) {
            if ((this.cancelarCfdiConOpcionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelarCfdiConOpcionesCompleted(this, new cancelarCfdiConOpcionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="integracionCfdi.ws.pade.mx", ResponseNamespace="integracionCfdi.ws.pade.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string acuseCancelacionCfdi([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contrato, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string uuid) {
            object[] results = this.Invoke("acuseCancelacionCfdi", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        uuid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void acuseCancelacionCfdiAsync(string contrato, string usuario, string passwd, string uuid) {
            this.acuseCancelacionCfdiAsync(contrato, usuario, passwd, uuid, null);
        }
        
        /// <remarks/>
        public void acuseCancelacionCfdiAsync(string contrato, string usuario, string passwd, string uuid, object userState) {
            if ((this.acuseCancelacionCfdiOperationCompleted == null)) {
                this.acuseCancelacionCfdiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnacuseCancelacionCfdiOperationCompleted);
            }
            this.InvokeAsync("acuseCancelacionCfdi", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        uuid}, this.acuseCancelacionCfdiOperationCompleted, userState);
        }
        
        private void OnacuseCancelacionCfdiOperationCompleted(object arg) {
            if ((this.acuseCancelacionCfdiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.acuseCancelacionCfdiCompleted(this, new acuseCancelacionCfdiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="integracionCfdi.ws.pade.mx", ResponseNamespace="integracionCfdi.ws.pade.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consultaCfdiPorUUID([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string contrato, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwd, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string uuid) {
            object[] results = this.Invoke("consultaCfdiPorUUID", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        uuid});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultaCfdiPorUUIDAsync(string contrato, string usuario, string passwd, string uuid) {
            this.consultaCfdiPorUUIDAsync(contrato, usuario, passwd, uuid, null);
        }
        
        /// <remarks/>
        public void consultaCfdiPorUUIDAsync(string contrato, string usuario, string passwd, string uuid, object userState) {
            if ((this.consultaCfdiPorUUIDOperationCompleted == null)) {
                this.consultaCfdiPorUUIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaCfdiPorUUIDOperationCompleted);
            }
            this.InvokeAsync("consultaCfdiPorUUID", new object[] {
                        contrato,
                        usuario,
                        passwd,
                        uuid}, this.consultaCfdiPorUUIDOperationCompleted, userState);
        }
        
        private void OnconsultaCfdiPorUUIDOperationCompleted(object arg) {
            if ((this.consultaCfdiPorUUIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaCfdiPorUUIDCompleted(this, new consultaCfdiPorUUIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void cancelarCfdiCompletedEventHandler(object sender, cancelarCfdiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelarCfdiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelarCfdiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void procesarArchivoCompletedEventHandler(object sender, procesarArchivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class procesarArchivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal procesarArchivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void obtenerXmlDesdeCsvCompletedEventHandler(object sender, obtenerXmlDesdeCsvCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class obtenerXmlDesdeCsvCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal obtenerXmlDesdeCsvCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void procesarArchivoConCSDCompletedEventHandler(object sender, procesarArchivoConCSDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class procesarArchivoConCSDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal procesarArchivoConCSDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void cancelarCfdiConOpcionesCompletedEventHandler(object sender, cancelarCfdiConOpcionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelarCfdiConOpcionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelarCfdiConOpcionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void acuseCancelacionCfdiCompletedEventHandler(object sender, acuseCancelacionCfdiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class acuseCancelacionCfdiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal acuseCancelacionCfdiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void consultaCfdiPorUUIDCompletedEventHandler(object sender, consultaCfdiPorUUIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaCfdiPorUUIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaCfdiPorUUIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591