//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSConecFM.WSLayoutFacturacionModerna {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://t2.facturacionmoderna.com/timbrado/soap", ConfigurationName="WSLayoutFacturacionModerna.Timbrado_ManagerPort")]
    public interface Timbrado_ManagerPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://t2.facturacionmoderna.com/timbrado/soap#consultaSectorPrimario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object consultaSectorPrimario(object request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://t2.facturacionmoderna.com/timbrado/soap#consultaSectorPrimario", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> consultaSectorPrimarioAsync(object request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://t2.facturacionmoderna.com/timbrado/soap#consultarSaldo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object consultarSaldo(object request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://t2.facturacionmoderna.com/timbrado/soap#consultarSaldo", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> consultarSaldoAsync(object request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://t2.facturacionmoderna.com/timbrado/soap#Auth", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool Auth(object param1, object param2);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://t2.facturacionmoderna.com/timbrado/soap#Auth", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<bool> AuthAsync(object param1, object param2);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://t2.facturacionmoderna.com/timbrado/soap#validarCFDI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object validarCFDI(object xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://t2.facturacionmoderna.com/timbrado/soap#validarCFDI", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> validarCFDIAsync(object xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://t2.facturacionmoderna.com/timbrado/soap#verificarCFDI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object verificarCFDI(object request, object @internal);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://t2.facturacionmoderna.com/timbrado/soap#verificarCFDI", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> verificarCFDIAsync(object request, object @internal);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://t2.facturacionmoderna.com/timbrado/soap#requestTimbrarCFDI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object requestTimbrarCFDI(object request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://t2.facturacionmoderna.com/timbrado/soap#requestTimbrarCFDI", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> requestTimbrarCFDIAsync(object request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://t2.facturacionmoderna.com/timbrado/soap#requestCancelarCFDI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object requestCancelarCFDI(object request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://t2.facturacionmoderna.com/timbrado/soap#requestCancelarCFDI", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> requestCancelarCFDIAsync(object request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://t2.facturacionmoderna.com/timbrado/soap#activarCancelacion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        object activarCancelacion(object request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://t2.facturacionmoderna.com/timbrado/soap#activarCancelacion", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<object> activarCancelacionAsync(object request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Timbrado_ManagerPortChannel : WSConecFM.WSLayoutFacturacionModerna.Timbrado_ManagerPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Timbrado_ManagerPortClient : System.ServiceModel.ClientBase<WSConecFM.WSLayoutFacturacionModerna.Timbrado_ManagerPort>, WSConecFM.WSLayoutFacturacionModerna.Timbrado_ManagerPort {
        
        public Timbrado_ManagerPortClient() {
        }
        
        public Timbrado_ManagerPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Timbrado_ManagerPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Timbrado_ManagerPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Timbrado_ManagerPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object consultaSectorPrimario(object request) {
            return base.Channel.consultaSectorPrimario(request);
        }
        
        public System.Threading.Tasks.Task<object> consultaSectorPrimarioAsync(object request) {
            return base.Channel.consultaSectorPrimarioAsync(request);
        }
        
        public object consultarSaldo(object request) {
            return base.Channel.consultarSaldo(request);
        }
        
        public System.Threading.Tasks.Task<object> consultarSaldoAsync(object request) {
            return base.Channel.consultarSaldoAsync(request);
        }
        
        public bool Auth(object param1, object param2) {
            return base.Channel.Auth(param1, param2);
        }
        
        public System.Threading.Tasks.Task<bool> AuthAsync(object param1, object param2) {
            return base.Channel.AuthAsync(param1, param2);
        }
        
        public object validarCFDI(object xml) {
            return base.Channel.validarCFDI(xml);
        }
        
        public System.Threading.Tasks.Task<object> validarCFDIAsync(object xml) {
            return base.Channel.validarCFDIAsync(xml);
        }
        
        public object verificarCFDI(object request, object @internal) {
            return base.Channel.verificarCFDI(request, @internal);
        }
        
        public System.Threading.Tasks.Task<object> verificarCFDIAsync(object request, object @internal) {
            return base.Channel.verificarCFDIAsync(request, @internal);
        }
        
        public object requestTimbrarCFDI(object request) {
            return base.Channel.requestTimbrarCFDI(request);
        }
        
        public System.Threading.Tasks.Task<object> requestTimbrarCFDIAsync(object request) {
            return base.Channel.requestTimbrarCFDIAsync(request);
        }
        
        public object requestCancelarCFDI(object request) {
            return base.Channel.requestCancelarCFDI(request);
        }
        
        public System.Threading.Tasks.Task<object> requestCancelarCFDIAsync(object request) {
            return base.Channel.requestCancelarCFDIAsync(request);
        }
        
        public object activarCancelacion(object request) {
            return base.Channel.activarCancelacion(request);
        }
        
        public System.Threading.Tasks.Task<object> activarCancelacionAsync(object request) {
            return base.Channel.activarCancelacionAsync(request);
        }
    }
}
